# Generated by Django 2.2 on 2021-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210305_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headre_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
