# Generated by Django 2.2 on 2021-03-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210305_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headre_image',
        ),
    ]
