# Generated by Django 2.2 on 2021-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210305_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headre_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
