# Generated by Django 2.2 on 2021-03-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_post_headre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headre_image',
        ),
    ]
