# Generated by Django 2.2 on 2021-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_post_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pick',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
