# Generated by Django 2.2 on 2021-03-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210305_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner_image',
        ),
    ]
